- name: configure backend server
  hosts: backend
  become: yes
  tasks: 
  - name: disable current module
    ansible.builtin.command: dnf module disable nodejs -y # In the command module we can directly use linux commands

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: create expense user 
    ansible.builtin.user:
      name: expense